export enum ActionType {
  MOVE_CELL,
  INSERT_CELL_AFTER,
  UPDATE_CELL,
  DELETE_CELL,
  BUNDLE_START,
  BUNDLE_COMPLETE,
  FETCH_CELLS,
  FETCH_CELLS_COMPLETE,
  FETCH_CELLS_ERROR,
  SAVE_CELLS_ERROR,
}
